name: Update Page

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Add ~/.local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install nushell
        run: |
          gh \
            --repo nushell/nushell release download \
            --pattern 'nu-*-x86_64-unknown-linux-gnu.tar.gz' \
            --output /tmp/nushell.tar.gz
          tar \
            --strip-components 1 \
            --wildcards --gzip --extract '*/nu' \
            --directory ~/.local/bin \
            --file /tmp/nushell.tar.gz

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.nu

  #     - name: Setup Pages
  #       id: pages
  #       uses: actions/configure-pages@v5

  #     - name: Build


  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3

  # # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{steps.deployment.outputs.page_url}}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
